### ISSUE TITLE
paid island creation?

### ISSUE THREAD

**Issue by sZerz** [tastybento/ASkyBlock-Bugs-N-Features#197]
Is it possible to make a paid island creation?

**Comment by Poslovitch** [comment]
Can you explain a bit more?

Do you mean to add buyable schematics?

**Comment by sZerz** [comment]
yep

**Comment by Poslovitch** [comment]
Just add a "cost: thevalueyouwant" line in their body

**Comment by ericsonm** [comment]
Hi Poslovitch,

Can you pls explain that a bit more.
Do you mean that players can buy different island styles with in game money?

Also, I don't mean to bend on this thread but when I tried to create my own starter island I have already reached the 256 height block limit. I followed the YT tutorial video by TastyBento and they said not to break the bedrock.
So can I break the original bedrock and replace it with a new bedrock but some blocks below the 256 limit, or can I change the confiq somehow so that new starter islands spawn at 128 blocks(half way). If that's possible can u pls teach me how to set up starter islands to spawn halfway.
Thx

**Comment by ericsonm** [comment]
I figured it out, you can use a second bedrock and not necessarily the original. So I can jst manually build a new starter island at 128 blocks or half way.

But can you please tell me if we can make multiple starter islands (individual designs, individual starter chests items etc) where players can pay in game money to buy?
Thx

**Comment by Poslovitch** [comment]
The players can buy island types (schematics) when they create an island if the schematicpanel is set to true in the configuration.

About the height of the island, check islandlevel (or islandheight) in the config. This is the y coordinate of the bedrock block from the schematic that will be pasted.

Breaking the bedrock block result in some bugs with islandgrid saves.

**Comment by ericsonm** [comment]
Hi 
When you leave a island should it not reset your island level back to nil or will ist say (lvl 0)?
Just wondering cheers :)
