### ISSUE TITLE
DisableOfflineRedstone lag

### ISSUE THREAD

**Issue by Fluxty** [tastybento/ASkyBlock-Bugs-N-Features#285]
Checking if any island members are online on BlockRedstoneEvent causes a ton of lag due to the incredibly high number of invocations. It's called and checked 403 times per tick on average on our server, and most of the stack trace is showing the lag coming from the loop over the island members. We're going to disable the setting for this reason, but there may be a way to not run these checks EVERY BlockRedStoneEvent, no?

**Comment by Poslovitch** [comment]
Actually, it's not possible : this «feature» already breaks a lot of redstone systems ; having it checking one out of two times would make the redstone more unstable.
This was never intended to be a stable feature (because the way redstone works just don't allow it to be stable) ; if this causes more problems than it solves, then disable it
