### ISSUE TITLE
Island Levels

### ISSUE THREAD

**Issue by Mickooo** [tastybento/ASkyBlock-Bugs-N-Features#297]
whenever people work on their island, the level is supposed to go up, but when I check it, it's always in the negatives and goes down more and more instead of going up. How do I fix this? It's a minor issue of course but it can still be very frustrating 

Thanks in advance
~Micko

**Comment by Poslovitch** [comment]
Are those players dying ?
Please send us your blockvalues.yml file.

**Comment by Mickooo** [comment]
No, they don't die, their island level just gets into the negatives, like I worked on my island for a bit and it went from 1 to 0 and when I work on it a bit more it'll get to -1.
I haven't changed the blockvalues.yml

**Comment by tastybento** [comment]
In the **console** do /asadmin level (name of player). This will provide you with a full level report that will show you what is happening with the scores and explain in a lot of detail why the level is what it is. I suggest you do it once, work on the island like you say and then do it again and compare the two.

**Comment by Mickooo** [comment]
That is what I did to see the levels of the island, like I said before, when a player works on the island the level goes down into the negatives, I got someone else to test it too and after he worked on his island for a bit I checked the level and it was at -3

**Comment by FilidDamhsoir** [comment]
Sounds like block values mate- happened to us too until I figured out what was going on. Early on players break higher value blocks (like grass) in order to get set up. They cut down trees (removing the points for each log and leaf) Level goes down, and then they build it back up once they start placing blocks again, but since the blocks they are placing aren't as valuable as grass it will go down for a while before slowly building back up.

**Comment by tastybento** [comment]
@FilidDamhsoir is probably right.

@Mickooo unless you see some problem between the two reports, there's no bug here. Ill close it for now.

**Comment by Poslovitch** [comment]
There will be a feature in 4.0 to set a minimum level that can't be reached ;)
