### ISSUE TITLE
Change world generation, help for new avventure.

### ISSUE THREAD

**Issue by HexGabbo** [tastybento/ASkyBlock-Bugs-N-Features#321]
By the way, I need to ask you a favor. I was planning to create an underground skyblock, but I do not know how to create a completely blocked world or change the generation of the same. a help?

**Comment by Poslovitch** [comment]
Well, this is currently not possible. However, it sounds great! We'll probably have a look to implement something like that.

**Comment by tastybento** [comment]
This is actually an undocumented feature:

In config.yml add this to the general section:

general:
   useowngenerator: true

When you do that, the ASkyBlock generator is completely turned off. You'll need to use your own generator plugin. We cannot give you any more help than that, but you will also need to change the blockvalues.yml file because players will have huge level values otherwise if you are underground.

Good luck!
