### ISSUE TITLE
Can't change world settings/spawn settings with /is settings

### ISSUE THREAD

**Issue by FrankHeijden** [tastybento/ASkyBlock-Bugs-N-Features#324]
heya,

i cant use the /is settings panel to modify the world settings of the spawn in-game. Also i changed "ANVIL: true" as setting in config.yml but its not working on my spawn, and in the /is settings panel its still displayed as disallowed.

Frank

**Comment by Poslovitch** [comment]
Can you send us your config.yml?

**Comment by FrankHeijden** [comment]
https://pastebin.com/tS85zZj8

**Comment by tastybento** [comment]
Sorry, I wasn't able to check the config and the pastebin has timed out. If this is still an issue, post it again please.

**Comment by FrankHeijden** [comment]
Yes its still an issue

**Comment by FrankHeijden** [comment]
https://pastebin.com/7HJFvPau

**Comment by tastybento** [comment]
Ah, even if you are Op, you still need the askyblock.settings.* perm to set settings. It's a bug, I'll fi it. Work around is to give yourself the perm.

As for changing settings in config.yml, they won't have any affect on any current island. They only affect new islands. If you want to flush the config.yml setting to all islands, you have to use /asadmin settingsreset and then hit tab to select the setting you want to flush. Otherwise flush all of them. For spawn, you'll need to use the GUI for settings completely.

**Comment by FrankHeijden** [comment]
That didn’t work for me unfortunately

**Comment by tastybento** [comment]
What version of the plugin are you using?

As Op, with askyblock.settings.* as a permission, when you go to your spawn island that you created by doing /asadmin setspawn, you should definitely be able to click on the icons to toggle their settings.
