### ISSUE TITLE
Players not taking damage from ghasts in nether

### ISSUE THREAD

**Issue by PugaBear** [tastybento/ASkyBlock-Bugs-N-Features#338]
This issue spans across all players; the island owner, team members, visitors, default rank and admin rank. (I made the island owner, who is an admin, a guest, made them relog, issue persisted) 

![image](https://user-images.githubusercontent.com/12417961/28195478-0a8edf9e-6810-11e7-810a-68d0993561a0.png)

**Comment by tastybento** [comment]
This is because in config.yml, allowtntdamage: false. The blast from the ghast is being considered as explosive damage so is being cancelled. A quick fix is to allow TNT damage.

However, I also see that Ghasts should be able to damage players normally, so I'll treat this as a bug and fix it in the next release.
