### ISSUE TITLE
Challenges GUI is not working

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#352]
/c complete challenge command is working but challenges GUI is not working for ASkyBlock 3.0.6.9 and Spigot 1.8. GUI is opening but cant click any items. 

I also tried the same challenges config in AcidIsland 3.0.5.4 and Spigot 1.8 it worked. If you wonder why am i still using 1.8 and not 1.8.8; because of this Spigot bug:
https://hub.spigotmc.org/jira/browse/SPIGOT-1110

Hoppers creates insane lag in 1.8.8 but in 1.8 there is no problem. Please fix gui problem.

NOTE: Minishop, control panel works. Only challenge gui isn't working.

**Comment by UnioDex** [comment]
Seems like someone already had that problem:
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/177

but i don't want to update 1.8.8 because of huge hopper lag. Can't we fix the problem in 1.8?

**Comment by Poslovitch** [comment]
Tastybento said we won't fix this bug as we would have to rewrite a dedicated ItemStack equality check as it isn't working in 1.8 only.

I can only suggest you to update to 1.12. Why stay on 1.8? PvP/PvE? There are tons of plugins that bring back the 1.8 combat experience. And there is a bunch of cool new features in Minecraft and even some in ASkyBlock that have been added in these more recent versions.

**Comment by UnioDex** [comment]
Players have prejudice for 1.12 they dont want to use it because of PvP (even if i install 1.8 PvP plugins). Also every server using 1.8 and they dont want to switch versions for one server.

**Comment by Poslovitch** [comment]
In that case, you should consider updating to 1.8.8 using PaperSpigot or even TacoSpigot. I'm quite sure they fixed the problem. Or, as Spigot's source code is open source, you may build yourself a 1.8 spigot containing the hopper fix.

We can't do much more for you. Maybe try to convince your players? 1.8 community is becoming an older community and is reducing, while the 1.12+ community keeps growing. I personally think this is stupid to stay on a version that brings nothing new because you don't want to switch on newer versions because of a single change.

Let's see what @tastybento will think of that, but I'm quite sure he shares my opinion.

**Comment by UnioDex** [comment]
Im using TacoSpigot. Unfortunately it does not solve the problem. I'll try to convince my players.
