### ISSUE TITLE
ASkyblock messes up custom advancements.

### ISSUE THREAD

**Issue by ShelLuser** [tastybento/ASkyBlock-Bugs-N-Features#397]
The moment skyblock is enabled it completely messes up the custom advancements on a server: they're not automatically loaded anymore (I need to use /minecraft:reload) and when the server is shut down / rebooted everything is reset back to default again.

I did some testing and can directly trace this unwanted behavior back to skyblock, and considering how handy advancements are I consider this a rather nasty bug. Right now we disabled skyblock because of it.

**Comment by Poslovitch** [comment]
ASkyBlock doesn't use advancements.
Our challenges are loaded by the plugin itself and therefore should not interfering with nothing whatsoever.

Can you give us the full list of plugins you are using, and the build of your server (`/version`) ?

**Comment by ShelLuser** [comment]
I only used Vault and Skyblock to determine the cause so I'm 100% sure it's caused by skyblock. When Skyblock is active my advancements are gone, when I remove it the advancement's are back. 

Server version:

[23:02:03 INFO]: This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Comment by Poslovitch** [comment]
Do you mean advancements that are added by a resource pack?

**Comment by ShelLuser** [comment]
No, custom advancements I made myself to cater to the survival session. Trust me: they're 100% correct where syntax & functionality is concerned.

**Comment by Poslovitch** [comment]
Hum. This bug is weird.
We never use/call anything that may be related to advancements.

Does it make errors in console?

**Comment by tastybento** [comment]
I've no idea why you'd have any issues with the plugin in this regard because like Poslovitch says, there's very little involved. There is one command run (that you can disable) that stops Command feedback (_minecraft:gamerule sendCommandFeedback false_).  You could try disabling that (set silencecommandfeedback: false in config.yml) What version of ASkyBlock were you trying?

For advancement errors, it might be useful to see what the failure log says. When an advancement fails for whatever reason, you can find failure messages in the Game Output window in the log files. See the Errors section [here](http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/commands-command-blocks-and/2809368-1-12-custom-advancements-aka-achievements).

**Comment by ShelLuser** [comment]
Sorry for a late response but.. There are no errors in the console. As I mentioned above: whenever Skyblock is active my custom advancements don't load. Only a /minecraft:reload activates them. Considering that this only happens when Skyblock is active I can only conclude that it's definitely related.

The only error I get is when I try to grant an advancement before issueing the reload; the system tells me that the advancement isn't there which is incorrect.

**Comment by tastybento** [comment]
I've no idea, this is way out of my experience level and as I don't have a way to replicate your issue (I don't know how to set up custom advancements) so I'm not sure how I can help. I have seen a [bug filed on custom advancements](https://hub.spigotmc.org/jira/browse/SPIGOT-3512) not loading properly until a reload on the Spigot hub where the issue was blamed on Multiverse core. Maybe (and this is a big maybe), the advancements are not loaded correctly when a plugin is one that is loaded at startup. i.e., load: startup is in the plugin.yml.
I'm going to close this right now. I suggest you try out some Bukkit plugins and see if you can find a common thread in terms of advancements not working.
