### ISSUE TITLE
Island being lost protection automaticly(like being unregister)

### ISSUE THREAD

**Issue by arnesacnussem** [tastybento/ASkyBlock-Bugs-N-Features#403]
Where I'm standing is my island,I can use /is to get back here 
But when I use /asadmin info , it says the island is not owned by anyone.

Besides.use /asadmin info sac(sac is my name in game),as the pic says my island is here.
![image](https://user-images.githubusercontent.com/9441546/29034238-3c666370-7bca-11e7-9126-9f85f60b0047.png)

Why my island being un-register? 
How can i disable the auto un-register?
How can i recovery those islands?

In addition to this i have try /asadmin register , but nothing happen.
![image](https://user-images.githubusercontent.com/9441546/29034826-1f10a8a6-7bcc-11e7-9fe6-082a244b8eb4.png)

**Comment by arnesacnussem** [comment]
so , is there anybody help me?

**Comment by tastybento** [comment]
Your islands.yml file has become corrupted or out of sync with the player files. This is most likely caused by a server crash. Make back ups and then stop the server, delete islands.yml and restart. It will rebuild the islands.yml file. All island settings will be reset to default. If you have island spawn, you'll need to make it again using /asadmin setspawn.

**Comment by arnesacnussem** [comment]
Thank you for your help.

Why not see this file as a runtime cache, you can regenerate this file every time the server launch.
