### ISSUE TITLE
Is Settings issues via /is settings AND via setIgsFlag( X , true) [API]

### ISSUE THREAD

**Issue by Fuizziy** [tastybento/ASkyBlock-Bugs-N-Features#412]
Hi,

I'm working with your API, and when I use
is.toggleIgs(SettingsFlag.VISITOR_ITEM_DROP);
or even
is.setIgsFlag(SettingsFlag.VISITOR_ITEM_DROP, true);

visitors are still not able to drop their items. I've seen something like that on the FAQ, typed the commands /asadmin settingsreset all and /asadmin settingsreset <SPECIFIC> but it did not work.

The .is settings panel shows ALL options as "Not allowed", even if, for instance, the mob spawning appears to be on TRUE. Talking about booleans, it seems like they WORK, as when I get the flag, it shows that it as been changed successfully, but it has no effect on the island behavior.

I've the lastest version, tried to delete the islands.yml, restart the island etc...

How can I deal with it ? Thanks a lot =)

**Comment by tastybento** [comment]
The reason is because the API only provides a copy of the Island object and not the object itself. I never anticipated that the Island would be manipulated directly.

You may want to get the Island directly by using plugin.getGrid().getIsland(playerUUID). It's not part of the API, but I'm never going to change that call.

**Comment by Fuizziy** [comment]
Thanks a lot. I Will try it out ;)

**Comment by tastybento** [comment]
Great!
