### ISSUE TITLE
ASkyblock crops dont grow

### ISSUE THREAD

**Issue by Suprreme** [tastybento/ASkyBlock-Bugs-N-Features#432]
So i installed the plugin a week and a half ago, and my players arent able to let crops grow. I dont know if there is a certain setting or what. Can you please help :) Also can you help out with challanges.yml because i have no clue how to change it and if there is a preset version please help :) But my main issue is the crops

**Comment by tastybento** [comment]
No, there's no setting and I haven't heard of this issue before. Are the players logging out? If the chunks aren't loaded then nothing will happen to the crops. If they hang around do they grow?

The best thing to do is read the challenges.yml comments.

**Comment by Suprreme** [comment]
Yes players are in the chunks of course. Should i re-install plugin?

**Comment by tastybento** [comment]
The plugin is not doing anything here to stop crops, so I'd say you need to look at the server. What version are you using and did you build it yourself using BuildTools.jar?

**Comment by Suprreme** [comment]
im using Spigot 1.8.8

**Comment by tastybento** [comment]
ASkyBlock should have absolutely nothing to do with this. I expect it's another plugin because there are a lot of servers running 1.8.8 without any issue.

The only way to solve this is to do the old "remove plugins until it works" trick. Remove plugins temporarily one by one and see if crops grow. Crop growing is a bit slow, so you'll need to give it at least 10 minutes per plugin. The type of plugins to target first are protection plugins. Good luck!
