### ISSUE TITLE
Lags problems

### ISSUE THREAD

**Issue by willperker** [tastybento/ASkyBlock-Bugs-N-Features#435]
Hi ! I encountered a problem on my server. We use ASkyBlock and with have many lags, the server has just 10 TPS in average...
We did a purge from 6 months, deleted the userdata from 6 months... That did'nt change anything. We saw there are many chunk loaded (4000 chunks for just 20 players..). I think the plugin ASkyBlock load some inutile chunk and create some lags, is it true?

**Comment by Poslovitch** [comment]
The plugin ASkyBlock doesn't load/unload any chunk (or at least, the only time where it could do that, is when it purges islands). You should then consider to optimize your server : prefer using PaperSpigot, configure bukkit.yml, spigot.yml and paper.yml properly, allocate more RAM.

The Skyblock mode is high-consuming, due to the huge amount of mob farms that are used simultaneously.

**Comment by willperker** [comment]
Okok,

thank you !
