### ISSUE TITLE
Citizens getting teleported

### ISSUE THREAD

**Issue by Pugabyte** [tastybento/ASkyBlock-Bugs-N-Features#474]
When I try to create NPCs in the skyblock world using [Citizens2](https://github.com/CitizensDev/Citizens2), it teleports them to the world spawn (and they proceed to fall into the void). I contacted the Citizens devs and they said it was likely due to ASkyBlock. Any ideas?

![Video](https://cdn.discordapp.com/attachments/315625512753954816/361011259384004608/citizens.gif)

![](https://i.imgur.com/BFsNPmo.png)

**Comment by tastybento** [comment]
Is your island locked?

**Comment by Pugabyte** [comment]
It happens even when in the spawn island

**Comment by tastybento** [comment]
Is the spawn locked?

Try this:

1. Go to the place where you want to spawn the citizen
2. Stop the server
3. Remove ASkyBlock.jar from plugins
4. Restart server and login
5. Create a Citizen 

Does it still get teleported? If not, then it's probably ASkyBlock, otherwise, it's something else.

I'll have a look at this tonight, but I can only think it'd be caused by islands being locked. Do /asadmin info where you stand and see if the area is locked or not.

**Comment by Pugabyte** [comment]
Neither my island nor the spawn is locked (I wasn't on my computer to check earlier).

Removing the plugin seems to have moved the area that NPCs are moved to. It is now inside the spawn island (no matter where I am in the world). This change persists after putting the plugin back. I will report this back to the Citizens devs as it seems like it isn't ASkyBlock

**Comment by tastybento** [comment]
You may want to remove all plugins except for Citizens to check it's not something else acting weirdly. Also, what server are you using?

**Comment by Pugabyte** [comment]
It was WorldGuard's entry: deny flag. My apologies
