### ISSUE TITLE
Not important small problem - lagging platform.

### ISSUE THREAD

**Issue by jodo1** [tastybento/ASkyBlock-Bugs-N-Features#476]
[https://youtu.be/GWhvRpVITnY](url)
This is not very important, but interesting issue.
(Yes, some players complained.)
When under block is not another block, this causing lag.
If player is near center of platform, lag is bigger.
I am not sure, if is it problem askyblock plugin.
server 1.8.8, java 8, askyblock protect (no worldguard)

(Excuse my bad english, I am from Czech republic.)

**Comment by tastybento** [comment]
This has been mentioned before. It is a minecraft thing - when placing a block over nothing, the lighting calculations of placing the block take a long time for some reason.

**Comment by tastybento** [comment]
So, the reason is that when you block out the light, every block below has to have the light level recalculated. It must do this until it hits something solid. As you are floating 120 blocks or so above nothing, it has to do this for a lot of blocks. There's not really much that can be done, unfortunately, so I'm going to close this.
