### ISSUE TITLE
I can't create a new challenge

### ISSUE THREAD

**Issue by Wreeper** [tastybento/ASkyBlock-Bugs-N-Features#478]
Hello , tastybento. I want to create a new challenge for players, for Elite, because at Elite there been no challenges.
Therefore, i found a problem. I cannot execute island commands since i added it. I removed it and turned back normal all.
See my challenge here:

    wreeper:
      friendlyname: 'Hungry Wree'
      description: 'Bake a cake, 2 breads, one milk and get a water bucket! Don't ask why.'
      icon: STONE_HOE
      level: 'Elite'
      type: inventory
      requiredItems: 'CAKE:1 BREAD:2 MILK_BUCKET:1 WATER_BUCKET:1'
      takeItems: true
      itemReward: 'DIAMOND_BLOCK:320'
      rewardText: '320 DIAMOND_BLOCK
      moneyReward: 250000
      expReward: 3000
      permissionReward: ''
      repeatable: true
      repeatItemReward: 'DIAMOND_BLOCK:2 DEADBUSH:2 SAND:2 GLASS:30'
      repeatRewardText: '2 DIAMOND BLOCK , 2 DEADBUSH , 2 SAND, 2 GLASS'
      repeatMoneyReward: 15000
      repeatExpReward: 150
      # Max times limits how many times a challenge can be done. Comment out to make unlimited
      maxtimes: 100

When i try to create a option in the Control Panel it gives the same error, but when i'm removing it it's fine.
My new Control Panel Option:

    10:
      material: BEACON
      description: '&aGo at Owner's Island. | &cBe careful!'
      command: '[island] warp Wreeper'
      nextsection: ''

If you want the version of the plugin, tell me how to check it.
Currently my server is on CraftBukkit-1.8.8

**Comment by tastybento** [comment]
Your YAML has a bug in it, you forgot the '  on this line:

rewardText: '320 DIAMOND_BLOCK

You can check YAML with online tools like this http://www.yamllint.com/

For the control panel, again there's a bug in your YAML due to '

description: '&aGo at Owner's Island. | &cBe careful!'

Look at the description and you will see a ' in the word Owner's. You can use double quotes instead:

description: "&aGo at Owner's Island. | &cBe careful!"

**Comment by Wreeper** [comment]
Thanks, i'm romanian.
