### ISSUE TITLE
Bug with settings

### ISSUE THREAD

**Issue by MrSkavix** [tastybento/ASkyBlock-Bugs-N-Features#482]
There's a problem with Monster Spawning setting. If player had a skeleton spawner and then changed setting, mobs still seem to spawn, even after destroying spawner. 
Only skeletons are spawning.

**Comment by tastybento** [comment]
Just to clarify, are these the replication steps?

1. Player's island setting for Mob Spawning is "Allowed" (Confirm?)
2. Player has skeleton spawner that spawns skeletons 
3. Player does /is settings and then clicks on the Mob Spawning icon and changes it to Disallowed (Confirm? If you are just changing config.yml that won't count until you push the settings change using the /asadmin settingsreset all command)
4. Skeletons still spawn from mob spawner
5. Player destroys mob spawner
6. Skeletons spawn naturally

**Comment by MrSkavix** [comment]
Yes, that's it.

**Comment by tastybento** [comment]
Are you using the latest version of the plugin and what server version are you using?

**Comment by tastybento** [comment]
Okay, confirmed. Something weird is going on here. I need to check into it.

**Comment by tastybento** [comment]
Actually, I remember now - in 3.0.7, the mob/monster spawning flags changed to only affect **natural** spawning. So, actually mob spawners will not be prevented from operating due to this flag (which makes sense. If you have a mob spawner then you should be able to use it because it cannot be crafted).
Having said that, the last part, where you say skeletons continue to spawn even if the spawner is broken - I can't replicate that. Are you sure?

**Comment by MrSkavix** [comment]
Yes, I'm sure. They spawn on entire island, not only at one place. There's only one kind of monsters - skeletons.

**Comment by tastybento** [comment]
I tried a lot of testing and the only issue I saw was that jockeys might be spawning, which may be getting through the filter. I also disabled chunk and default spawning.
