### ISSUE TITLE
Please help!!

### ISSUE THREAD

**Issue by wizdamrisby** [tastybento/ASkyBlock-Bugs-N-Features#495]
How do i make it so when people make islands they dont see my hub in the air??

**Comment by Poslovitch** [comment]
Instead of opening an issue each time you have a question, check the FAQ first, then _read_ - yes, I said **read** - the comments in the config (they are here to help you about what does what), then try to google a bit by yourself.
Lots of people probably already answered to this question on a few forums. Maybe even in your native language (in case you're not an english native speaker).

This GitHub is mainly for bug fixing, and we haven't got so much time to spend on such questions.
