### ISSUE TITLE
Island#getEntities() always returns null

### ISSUE THREAD

**Issue by fordross** [tastybento/ASkyBlock-Bugs-N-Features#505]
I'm thinking there must be something simple that I'm missing, but I can't guess what it is.  can be standing on the starter island having spawned 3 villagers, and still get this result.  Any pointers what I did wrong?  Thanks!

Spigot 1.12.2 with AcidIsland 3.0.7

	@Override
	public void onCommand(CommandSender s, Command cmd, String label, String[] arg) {
		Player p = (Player)s;
		ASkyBlockAPI aiApi = ASkyBlockAPI.getInstance();
		Island is = aiApi.getIslandOwnedBy(p.getUniqueId());

		// This works exactly as expected
		int hopperCount = is.getHopperCount();
		// 

		HashMap<EntityType, Integer> entities = is.getEntities();

		// This always equals 0
		int mapSize = entities.size();

		// This always equals 0
		int villager = is.getEntity(EntityType.VILLAGER);

		// This will always throw NPE
		int villagerCount = entities.get(EntityType.VILLAGER);
	}

**Comment by tastybento** [comment]
Ah, that code is not used anymore. At one time, the island held an entity count. It doesn't anymore but the code was not removed. Sorry.
Have a look at the EntityLimits class for how I count entities. Basically, Bukkit can give you the entities in a chunk. I loop through all the chunks in a island. Technically, this could count entities outside of the player's island boundary because the chunk boundary may overflow the island boundary, but it does not usually matter unless the islands are completely adjacent to each other.

**Comment by fordross** [comment]
No reason to be sorry at all!  Thanks for your help!
