### ISSUE TITLE
Start commands doesn't work

### ISSUE THREAD

**Issue by Dodlur** [tastybento/ASkyBlock-Bugs-N-Features#519]
I wanted to have islands separated by 100 blocks and to have 99 of protection, but even if i type 99 in the config file, when i create an island, it has 98. I have to type the command myself /asadmin setrange "player" 99. Then it works.
So i wanted to put this comman /asadmin setrange [player] 99 in the startcommands.
but starts commands, reset commands, leave commands, all of these doesn't work...
Even kit or balance commands doesn't work.

**Comment by tastybento** [comment]
You can't set the protection to 99, it has to be an even number (it says in the config.yml). The reason is because 100 means 50 blocks in opposite directions. So 98 gives you one block all the way around.

For the start commands, is your YML correct? Check your config with a YAML checker. Commands must look like this:

```
   # Commands to execute when a player starts a new island for the first time - NOT a reset
   startcommands:
   - "asadmin lock [player]"
   - "[SELF] balance"
   - "[SELF] kit tools"
```

Also, check the console log to see if there are any errors. Your players might not have the right permissions to run commands, for example.
