### ISSUE TITLE
The /is or /island command creates error on console but island command still works. 

### ISSUE THREAD

**Issue by Jager67** [tastybento/ASkyBlock-Bugs-N-Features#552]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
Thermos 1.7.10 1614
**Plugin version:**
askyblock v3.0.8.2
**What other plugins are you using? (do /plugins and paste here)**
WorldEdit, KeepItems, Essentials, LogBlock, BetterChunkLoader, ClearLag, EasyBackup, Votifier, ConsoleSpamFix, ProtocolLib, WorldGuard, EssentialsChat, BanItem, PermissionsEx, GAListener, Vault, EssentialsSpawn, EnjinMinecraftPlugin, Autorank, ASkyBlock, Plan, Multiverse-Core, DiscordSRV, GriefPreventionPlus, GPPRealEstate
**Description of issue. What happened?**
After updating players use the command /is or /island an error pops up on the console and in game but the island command still works I just don't want everything to get corrupt or have issue down the road.
**Steps to make this happen**

1. Player's use the command /is or island 
2. Console example of what error pops up. https://pastebin.com/1E0EWfGD
3. Player ends up at there island just an error will pop up for using that command.

**What do you think should happen?**
Never seen the error before the update.
[fml-server-latest.log](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1490405/fml-server-latest.log)

**Comment by tastybento** [comment]
This is caused by code that was added to make sure that NPC's or named mobs would not be removed when a player teleports to their island and the **remove mobs** setting is active. The call uses getCustomName, which your server doesn't support. This was in the [1.7.10 API,](http://www.javaminecraft.com/bukkitapi/org/bukkit/entity/LivingEntity.html) so I'm not sure why it's not in your Thermos build. These are your options:

1. Update your server to something more recent. 
2. Turn off the remove mobs on island teleport option (in config.yml)
3. Build your own version of the plugin from source with this bit removed.
