### ISSUE TITLE
Timing out on newer paperspigot versions

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/ASkyBlock-Bugs-N-Features#610]
I updated the paperspigot version and the server was timing out, any player could join. I removed plugins one by one and it seems that ASkyBlock is causing the problem, the latest log on console is: 
[ASkyBlock] Loading warps...

ASkyBlock version: 3.0.8.2
PaperSpigot version when it works fine: 1248
Latest PaperSpigot and it doesn't work: 1316

**Comment by Poslovitch** [comment]
Please provide the full log, interesting data might be there.

Please keep in mind that we may not be able to find a fix. ASkyBlock officially supports Spigot, not its forks such as PaperSpigot or TacoSpigot, etc. Therefore, you may also have to file an other bug report on PaperSpigot's bug tracker and provide a link to this issue.

I personally don't think the problem comes from our side, and that it rather comes from a change in the recent PaperSpigot builds, but let's see the logs first.
