### ISSUE TITLE
Block levels not matching the config

### ISSUE THREAD

**Issue by ItzAntony** [tastybento/ASkyBlock-Bugs-N-Features#629]
**Server Version**
1.12.2

**Plugin version:**
Latest - V3.0.8.2

**Description of issue. What happened?**
Island levels are not calculating the same as placed into the config. I have the default level set to 100 so so if someone placed 100 blocks that are worth 1 then their island level should be 1. I have set diamond blocks to 100 so each of them placed is worth 1 level. This for some reason is not the case. I have placed 100 blocks down and the island is only worth level 97.

**Steps to make this happen**

1. Set the block value of diamond to 100
2. Set the levelcost to 100 (Default)
3. Remove everything from the island protected area and place 100 diamond blocks, you should be level 97.

**What do you think should happen?**
I think that if you place 100 diamond blocks that are worth 100 each, you would be level 100.

**Comment by tastybento** [comment]
Check the levelhandicap setting in schematicconfig. That deducts levels so that players can start with level 0. The fact that you are seeing 3 less makes me think the level of the initial island is 3. 

Also, in the console do /asadmin level <name> because that'll give you a full report on everything so you'll be able to work out what is being deducted and why.

**Comment by ItzAntony** [comment]
I've set the handicap to 0 and restarted the server. Created a new island and the levels are still the same.

**Comment by tastybento** [comment]
Ok!
