### ISSUE TITLE
Minecraft::ASkyBlock - Lighting Queue LAG PROBLEM

### ISSUE THREAD

**Issue by Y3ko** [tastybento/ASkyBlock-Bugs-N-Features#653]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version: 1.12.2**

**Plugin version: Latest**

**What other plugins are you using? (http://prntscr.com/iicfr2)**

**Description of issue. What happened?**
My server is lagging by Minecraft::ASkyBlock - Lighting Queue

**I don't know how it's happening... Too many times my server is lagging because of this.**
How can i fix it? 

MY TIMINGS REPORT: https://timings.aikar.co/?id=1eb5c0079f0e4ef09e3279dc546b5822

**Comment by tastybento** [comment]
Lighting Queue issues are related to the world itself, not the plugin. You may have a corrupted chunk somewhere. I recommend you use region fixer - https://www.spigotmc.org/wiki/using-the-minecraft-region-fixer/

Also, looking at your timing report, you have > 2000 hoppers per tick that are being serviced. You should watch that it doesn't grow too much otherwise you will see a lot of lag from hoppers. Make sure you limit hoppers per island.

**Comment by Y3ko** [comment]
@tastybento We did it but there is nothing...
https://puu.sh/zwyAj/f6ed63d650.png

**Comment by tastybento** [comment]
Do you use a custom schematic? Is it big?

**Comment by Y3ko** [comment]
No we don't have. Classic ASkyBlock Island.

**Comment by tastybento** [comment]
I don't think this is fixable. Closing.
