### ISSUE TITLE
AcidIsland: House Challenge: Wood Door Type

### ISSUE THREAD

**Issue by ScuroK** [tastybento/ASkyBlock-Bugs-N-Features#688]
Could you make it possible in AcidIsland to allow any wooden door in the "build a house" challenge?

Players often dont understand why its not working if they build a door from another wood type than oak.

**Comment by Poslovitch** [comment]
That's due to how Material in Spigot works. OAK_DOOR is different from SPRUCE_DOOR, etc... and we don't have any way to just ask for "doors" and/or that would take too much time, which we wouldn't take because ASB is in maintenance mode (bug fixes only).

This is a feature which is planned for BSkyBlock, because 1.13 will allow us to do more generic scans.
