### ISSUE TITLE
Change gamemode every time you move to island?

### ISSUE THREAD

**Issue by Baw-Appie** [tastybento/ASkyBlock-Bugs-N-Features#797]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.12.2
**Plugin version:**
3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
This issue occurred after updating the plugin.
We used version 3.0.7.
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Every time I go to Island, I switch to spectator mode with the message "Your game mode has been updated" and then switch back to survival mode.

How do I disable this feature?
**Steps to make this happen**

1. Regenerate the island.
2. Go to the island.
3. The problem occurs.

**What do you think should happen?**
I don't know about plug-in development,
https://gisub.com/tstybento/askyblock/blob/9ae5a4a85e10a166161c61v708c708c8ff99/src/com/wasteoflactic/askileute/altuteuteuteuteuteuteuteute/
I think it would be necessary to modify it to operate according to the config.

(I'm sorry I don't speak English.)

**Comment by tastybento** [comment]
Yes, during teleport, players are put into Spectator mode to keep them safe. Then they are put back to Survival mode to continue the game. The teleporting time made be quite long depending on whether a safe spot can be found or not. So, this is not a bug, but by design.

Normally, you see no message, but as you are, do this:

/gamerule sendCommandFeedback false
