### ISSUE TITLE
AcidIsland worlds being forced set to EASY difficulty

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#802]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paperspigot 1441 1.12.2
**Plugin version:**
V3.0.8.8
**Description of issue. What happened?**
AcidIsland worlds (AcidIsland and AcidIsland_nether) have their difficulties forced set to EASY whenever I restart the server.
**Steps to make this happen**

1.  Check the difficulty of an AcidIsland world through client settings.

**What do you think should happen?**
AcidIsland worlds should use the global difficulty from server.properties.

**Comment by tastybento** [comment]
So... you are correct in that the world always gets set to easy. However, the server.properties difficulty setting is only applied to the standard worlds by the server, e.g., world, world_nether, etc. and not to extra worlds made by the Bukkit API. In order to set the world difficulty and have it stick for these multi worlds, you need to use a plugin like MultiverseCore, where you can do for example,  **/mv modify set difficulty 3**. Multiverse then remembers the difficulty and sets it every server reboot. Alternatively, if AcidIsland is the main world on the server, then the difficulty should stick too.

Adding a persistent difficulty setting to AcidIsland could be done, there isn't actually a way to grab the server default setting from server.properties except via a circuitous route of trying to get the main world and then querying its difficulty. That may work. I'll have to see if that's possible. Also, it could clash with Multiverse settings too. So, my recommendation is for now to use Multiverse to set it.

**Comment by TheWranger** [comment]
Will do, thanks.
